ci/get-ocp-repo.sh: add --enablerepo when installing centos packages
This PR: https://github.com/openshift/release/pull/62296 now builds scos
images. The extensions image build hit this error:

```
INFO: Neutering RHEL repos for SCOS
centos-stream-release-9.0-26.el9.noarch
package centos-release-cloud is not installed
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
```

This is because the centos-release* repos are disabled in the node image
which is used for building extensions