cloud: fix sha256sum generation
When the 'metadata' stage went to production, it blew up on the
generating `sha256sum` step with an error like this:

```
java.lang.NoSuchMethodError: No such DSL method 'sha256sum
/srv/rhcos/output/images/cloud/...
```

Since it worked on my test Jenkins, I'm just taking a guess that the
use of double-quotes around the `awk` command confused the DSL parser.

So this might fix it, but it might continue to fail...