rhsm: add `rhsm.conf` which is from `subscription-manager`
`rhsm.conf` (from `subscription-manager`) is missing on RHCOS,
which causes `rpm-ostree install <pkg>` failed with entitlement
build, as the SSL CA cert path is wrong to set
`/etc/rhsm-host-host/ca/redhat-uep.pem`.

```
STEP 3/5: RUN rpm-ostree install libreswan

error: Updating rpm-md repo 'rhel-9-for-x86_64-baseos-rpms': cannot update repo 'rhel-9-for-x86_64-baseos-rpms': Cannot download repomd.xml: Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://cdn.redhat.com/content/dist/rhel9/9/x86_64/baseos/os/repodata/repomd.xml [error setting certificate file: /etc/rhsm-host-host/ca/redhat-uep.pem]
error: build error: building at STEP "RUN rpm-ostree install libreswan": while running runtime: exit status 1
```

https://issues.redhat.com/browse/RHEL-1451 meant to track from
`librhsm` side, but was closed because of risky.

Fixes: https://issues.redhat.com/browse/OCPBUGS-11181