Revert "prow: Also pull in 4.13 temporarily"
CI is failing because the the mirrored 4.13 and 4.14 RHEL 9.2 repos
in openshift/release are pointing to different locations but defining
the same `rhel-9.2-baseos` and `rhel-9.2-appstream` repos:
- ocp-4.13-rhel92.repo is pointing at beta content
- ocp-4.14-rhel92.repo is pointing at eus content

Normally this would not be an issue but c0ca55d pulled in the 4.13
repo file to workaround the 4.14 OSE repo not having podman. During
`cosa fetch` rpm-ostree would fail with random package download
errors.

```
Will download: 514 packages (848.5?MB)
Downloading from 'rhel-9.2-fast-datapath'...done
Downloading from 'rhel-9.2-appstream'...done
error: Cannot download Packages/n/nmstate-2.2.10-2.el9_2.x86_64.rpm: All mirrors were tried; Last error: Status code: 404 for http://base-4-13-rhel92.ocp.svc.cluster.local/rhel-9.2-appstream/Packages/g/git-core-2.39.3-1.el9_2.x86_64.rpm (IP: 172.30.206.47)
error: failed to execute cmd-fetch: exit status 1
```

This reverts commit c0ca55db1863a511cdbf96eade18bb7cb0f77ca3.